### ISSUE TITLE
Replace GraphQL Client

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-interface#1368]

**Comment by adamgall** [comment]
@Da-Colon can you please give some more context to this issue?

**Comment by Da-Colon** [comment]
I dove into this setup, along with looking at the examples at https://github.com/graphprotocol/graph-client/tree/main/examples. I'm eager to remove the weirdness around the weird build warnings, but for now this appear to be caused by NextJS infrastructure using the AppRouter and the inferred ServerComponents. This is still largely assumptive. I've also played with different setups and  read through some stackoverflows about related issues with no real solutions that I can get to work currently. 

Going to Close for now
