### ISSUE TITLE
Add Bug Bounty link to immunefi on the website

### ISSUE THREAD

**Issue by dannydecent** [decent-dao/fractal-interface#271]

**Comment by adamgall** [comment]
@dannydecent where in the app are you thinking this should go? in the menu dropdown?

**Comment by dannydecent** [comment]
@adamgall yes. was still thinking it through. 100% on the fractal website, and the only place in the app would be in the drop down. working through options or if it even lives in app. thoughts? (side note, would this be better in discussions?)

**Comment by adamgall** [comment]
reason i ask, is because you put this issue into the `fractal-interface` repository. issues in this github repository should always result in a change to the `fractal-interface` codebase (the webapp).

i'd say, just create the card in the "project" (and don't "turn it into an issue on a codebase repo") if it's not sure where the change will occur yet.

we don't have a codebase repo for the notion.so marketing site, so yeah, idk the best way to track tasks/changes to that thing. maybe just by leaving the cards in the github project board unassigned to any specific repo.

**Comment by dannydecent** [comment]
i smell what you cookin'

**Comment by Da-Colon** [comment]
outdated
