### ISSUE TITLE
Tokens required for creating a proposal

### ISSUE THREAD

**Issue by christopherdancy** [decent-dao/fractal-interface#338]
If a DAO requires users to have a token allocation before creating a proposal. We should check this on the frontend so the user does not revert a transaction.

**Comment by Da-Colon** [comment]
To clarify we need add some validation to check for voting power and  disable the 'create a proposal` button if a user doesn't have voting power?

**Comment by adamgall** [comment]
Yes, exactly. A Governance module is configured to require a user holds `x` governance tokens in order to create a proposal. I believe our UI defaults that to `0` (during the DAO creation process). The UI is also _assuming_ it's `0` in the Proposals component, because it always allows any user to attempt to create a Proposal.

The UI should check that the connected user's governance token balance is >= the configured token amount needed to create a proposal, before allowing the user into that "create a proposal" workflow.
