### ISSUE TITLE
"Execute" button triggers failed transaction if clicked "immediately" after it becomes enabled

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#390]
The onClick fails if click right when it appears. The contract method isn't quite ready yet and there should be a hardcoded delay to prevent an error if it's too early

**Comment by adamgall** [comment]
this is probably an Off By One error with the block number

**Comment by adamgall** [comment]
I'm not sure why (the logic seems right), but I can't help but think the issue is on this line (or maybe the data behind the scenes that this line acts upon)

[        proposal.eta < currentTimestamp](https://github.com/decent-dao/fractal-interface/blob/d56a40e9e9808e6bf69a044012e59cc37c50f2c1/src/components/Proposals/ProposalExecute.tsx#L22)

**Comment by Jonny-Ringo** [comment]
> 

I had this same issue a couple of times when I was doing spinnups to check it out. I set my Block time delay to 0 so execution is allowed immediately. If clicking execute right when it was available I got a console error about the delay(shoulda captured that log) but it cleared up after maybe 30 seconds and then went through.

**Comment by Da-Colon** [comment]
no longer applies
