### ISSUE TITLE
Gnosis Safe incorrect prediction

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#430]
So Once I got the Workflow working. and checked the address supplied by the GnosisWrapper Contract, I noticed that it links to the implementation contract and not the Gnosis Predicted Address.

See below comment. TLDR: This prediction isn't accurate

`src/hooks/useCreateGnosisDAODataCreator.ts` line 114
```ts
      const predictedGnosisSafeAddress = ethers.utils.getCreate2Address(
        addresses.gnosisSafeFactory.address,
        ethers.utils.solidityKeccak256(
          ['bytes', 'uint256'],
          [ethers.utils.solidityKeccak256(['bytes'], [gnosisSafeFactoryCalldata]), gnosisSafeSalt]
        ),
        ethers.utils.solidityKeccak256(
          ['bytes', 'uint256'],
          [proxyCreationCode, addresses.gnosisSafe.address]
        )
      );
```

**Comment by adamgall** [comment]
What needs to be fixed? It's not clear to me what the issue is.

**Comment by Da-Colon** [comment]
So two things I think. 

First is the address that is being passed into the `gnosisWrapperFactoryCalldata` I believe should be the `predictedGnosisSafeAddress`

```ts
      const gnosisWrapperFactoryCalldata = [
        abiCoder.encode(['address'], [predictedAccessControlAddress]),
        abiCoder.encode(['address'], [addresses.gnosisSafe.address]), <--------- should be switched
        abiCoder.encode(['address'], [addresses.gnosisWrapper.address]),
        abiCoder.encode(['bytes32'], [gnosisWrapperSalt]),
      ];
```

The second problem, is that the predictedAddress is incorrect. same problem as before that a contract does not get created at this address. This link (bottom of page) talks about how the Create2 should be created ` https://safe-docs.dev.gnosisdev.com/safe/docs/contracts_deployment/.  see lines 108-124 `src/hooks/useCreateGnosisDAODataCreator.ts`

**Comment by Da-Colon** [comment]
So When I fixed the link the button directs to. This kinda shows the first problem. Here is the link it creates. the address it is getting from the contract currently is the implementation address from `.env` 

https://gnosis-safe.io/app/gor:0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552/home. It recognizes it as a Gnosis Safe but fails to load.

**Comment by Da-Colon** [comment]
Was reading up on the Gnosis Contracts and following our creation process and prediction. I decided to create a gnosis safe in their UI and ran into a problem. It appears they on Goerli something isn't right with the contracts themselves, It looks like thier prediction modal is not only off (address that is saved in local storage for Gnosis Safe is just a plain address), but also when you put the Gnosis's safe Proxy address into the UI the safe doesn't load. 

Will continue looking into this

**Comment by Da-Colon** [comment]
There we go from the Gnosis Discord. 



![Image](https://user-images.githubusercontent.com/38386583/185803557-b67011a5-c29d-4c67-964c-7e7dad0d66f0.png)

@adamgall @tbwebb22 @christopherdancy

**Comment by adamgall** [comment]
@Da-Colon good find.

do you know if the issue is simply with the gnosis UI, or the gnosis factory/implementation contracts themselves on goerli?

**Comment by adamgall** [comment]
I just created a new Safe on Goerli using the Gnosis UI, and it's true that the newly created Safe won't load up for me in their UI.

But, the address that was saved into my Local Storage does match the address from the Transaction logs on Etherscan.

First, here's the transaction of me creating a new Safe on Goerli using the Gnosis UI
https://goerli.etherscan.io/tx/0x5af1a85a3e0ae3bcee0f351604d31a2c4c235a459705773f9f0c11f29fca676a

Here's a screenshot of the "Logs" tab, showing the address of the new Safe `0x8f5Abc19282499BFd2663FcB
![Screen Shot 2022-08-21 at 3 26 55 PM](https://user-images.githubusercontent.com/706929/185807682-1477b21a-8ad7-45f2-8167-63aad42a5267.png)
1dDEcCd24A20D6AA`

I know that's the Safe address because of the last section of this Gnosis help article:
https://help.gnosis-safe.io/en/articles/4971293-i-don-t-remember-my-safe-address-where-can-i-find-it

Here's a screenshot of my local storage, directly after creating that new Safe
![Screen Shot 2022-08-21 at 3 26 03 PM](https://user-images.githubusercontent.com/706929/185807628-4ef62483-ffd9-417d-a4e7-096ba5ee3955.png)

When attempting to load this Safe in the UI, and viewing console logs, the Gnosis API returns a 404 on this GET request:
https://safe-client.gnosis.io/v1/chains/5/safes/0x8f5Abc19282499BFd2663FcB1dDEcCd24A20D6AA

So, I wonder if the issue is just with their API?

So what am I even trying to say here... not really sure. It _seems_ like the contracts work. My gut says we should be able to predict what the deployed Gnosis Safe address is. But, it won't load up in their UI.

**Comment by Da-Colon** [comment]
hahha I got it

**Comment by Da-Colon** [comment]
Give me a bit and I'll plus up the code. I also see a way to clean this up a little bit
