### ISSUE TITLE
Bug: Investigate determining locked Metamask wallet

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#608]
### Overview

Currently if your Metamask wallet is password locked, clicking "Connect Wallet" will do nothing, with no user feedback.

We should see if it's possible to determine this state, and give a message to the user as to what is happening.

Also test other wallets with for the same issue.

### Steps to reproduce

1. Lock your Metamask wallet
2. Click "Connect Wallet" in the Fractal app
3. nothing occurs, no response to the user and Metamask does not trigger in any way

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

All

### web3 wallet

MetaMask

**Comment by adamgall** [comment]
This works for me, as expected, on fresh Firefox and fresh Fractal app (no state, all history / cache / etc cleared) with a locked MetaMask. The locked MetaMask window pops up / foregrounds.

https://user-images.githubusercontent.com/706929/198718780-03a64427-0863-4133-933c-31daf52f171c.mov

I suspect the behavior experienced in OP is due to some stale state.

**Comment by herbig** [comment]
> This works for me, as expected, on fresh Firefox and fresh Fractal app (no state, all history / cache / etc cleared) with a locked MetaMask. The locked MetaMask window pops up / foregrounds.
> Screen.Recording.2022-10-28.at.3.38.32.PM.mov
> 
> I suspect the behavior experienced in OP is due to some stale state.

Hmmm, strange. Yeah I'll have to test this some more and see what the issue is, it's likely just me..

**Comment by herbig** [comment]
I haven't seen or been able to replicate this again.  Closing this for now.
