### ISSUE TITLE
Side NavItems show on Welcome screen.

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#793]
To Reproduce:
- Load in a DAO
- Click on Fractal F logo (top-right)

![Image](https://user-images.githubusercontent.com/38386583/207702676-0dea3075-91d9-4df7-91e9-b32a70711f88.png)

**Comment by herbig** [comment]
Ah weird, good catch. I've never noticed that before..

**Comment by herbig** [comment]
@Da-Colon maybe you can give me guidance on this...

I tried `GnosisAction.INVALIDATE` for this:

```
<Link
        data-testid="sidebarLogo-homeLink"
        to={BASE_ROUTES.landing}
        onClick={() => {
          gnosisDispatch({ type: GnosisAction.INVALIDATE });
        }}
        aria-label={t('ariaLabelFractalBrand')}
>
```

But that breaks when you click the browser back, since now you're still invalidated and have no DAO loaded.

But if I go back and forth between two DAOs, it works fine.  So might be some React solution I'm unaware of here.
